=== Jcorvil/LMSGIExamenUD4/Ejercicio1/losremediosSA.dtd
<!ELEMENT losremediosSA (sucursal)>
<!ELEMENT sucursal (albaran*)>
<!ELEMENT albaran (zonaExposicion, zonaGestion)>
<!ELEMENT zonaExposicion (codSucursal, trabajador, fechaPedido, observacionPedido)>
<!ELEMENT codSucursal (#PCDATA)>
<!ELEMENT trabajador (#PCDATA)>
<!ELEMENT fechaPedido (#PCDATA)>
<!ELEMENT observacionPedido (#PCDATA)>
<!ATTLIST codSucursal codigo CDATA #IMPLIED>
<!ATTLIST observacionPedido valores CDATA #IMPLIED>
<!ELEMENT zonaGestion (codigoArticulo, unidades, precioUnidad, observacionArticulo, plazorevision)>
<!ELEMENT codigoArticulo (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precioUnidad (#PCDATA)>
<!ELEMENT observacionArticulo (#PCDATA)>
<!ELEMENT plazorevision (#PCDATA)>
<!ATTLIST codigoArticulo codigo CDATA #IMPLIED>
<!ATTLIST plazorevision intervalo CDATA #IMPLIED>

=== Jcorvil/LMSGIExamenUD4/Ejercicio1/losremediosSA_D.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE losremediosSA SYSTEM "losremediosSA.dtd">
<losremediosSA>
    <sucursal>
        <albaran>
            <zonaExposicion>
                <codSucursal codigo="X1234567">A1458798</codSucursal>
                <trabajador>Jorge</trabajador>
                <fechaPedido>10/02/2023</fechaPedido>
                <observacionPedido valores="Urgente/Incompleto">Urgente</observacionPedido>
            </zonaExposicion>
            <zonaGestion>
                <codigoArticulo codigo="ABC-1-2-3">GFT-5-7-9</codigoArticulo>
                <unidades>3</unidades>
                <precioUnidad>15</precioUnidad>
                <observacionArticulo>Entrega r√°pida</observacionArticulo>
                <plazorevision intervalo="Dias">30</plazorevision>
            </zonaGestion>
        </albaran>
    </sucursal>
</losremediosSA>
